default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: radio-sort
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: radio-sort_development

test:
  <<: *default
  database: radio-sort_test
  host: localhost

production:
  <<: *default
  database: radio-sort_production
  username: radio-sort
  password: <%= ENV['RADIO-SORT_DATABASE_PASSWORD'] %>
